---
permalink: sm-hardware/what-are-icmp-ping-responses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, icmp, ping, responses, message, protocol, 
summary: 'El protocolo de mensajes de control de Internet (ICMP) es uno de los protocolos de la suite TCP/IP.' 
---
= ¿Qué son las respuestas PING de ICMP?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El protocolo de mensajes de control de Internet (ICMP) es uno de los protocolos de la suite TCP/IP.

 `ICMP echo request`Y los(`ICMP echo reply` mensajes se conocen comúnmente como `ping` mensajes. `Ping` es una herramienta para la solución de problemas que usan los administradores del sistema para probar manualmente la conectividad entre dispositivos de red, y también para probar la demora de la red y la pérdida de paquetes.  `ping`El comando envía un `ICMP echo request` a un dispositivo de la red, y el dispositivo responde inmediatamente con un(`ICMP echo reply`. A veces, la política de seguridad de red de una empresa requiere que `ping` (`ICMP echo reply`) esté desactivada en todos los dispositivos para que sea más difícil de detectar por personas no autorizadas.
