---
permalink: san-getstarted/login-um.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, log in Unified Manager 
summary: Acceda e inicie sesión en Unified Manager. 
---
= Acceda a Unified Manager de SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tras instalar el proxy de servicios web, puede acceder a SANtricity Unified Manager para gestionar varios sistemas de almacenamiento en una interfaz basada en web.


NOTE: Para conocer los navegadores compatibles, consulte link:supported-browsers-os.html["Exploradores compatibles y sistemas operativos"].

.Pasos
. Abra un explorador e introduzca la siguiente URL:
+
`+http[s]://<server>:<port>/um+`

+
En esta URL, `<server>` representa la dirección IP o el FQDN del servidor donde se instaló Web Services Proxy y `<port>` representa el número de puerto de escucha (el número predeterminado es 8080 para HTTP y 8443 para HTTPS).

+
Se abrirá la página de inicio de sesión en Unified Manager.

. Cuando inicie sesión por primera vez, introduzca `admin` el nombre de usuario y, a continuación, defina la contraseña del usuario admin y confírmela.
+
La contraseña puede tener hasta 30 caracteres.



Para obtener más información sobre los usuarios y las contraseñas, consulte link:../um-certificates/how-access-management-works-unified.html["Cómo funciona Access Management"].
